# SwiftLint Configuration for OpenClaw Shield

disabled_rules:
  - trailing_whitespace  # Can be noisy
  - line_length          # We'll set a custom limit

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - private_outlet
  - private_action

included:
  - OpenClawShieldMenuBar

excluded:
  - Pods
  - .build
  - DerivedData

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y

reporter: "xcode"
